package lt.vu.mybatis.model;

public class ItemCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM_CATEGORY.ITEM_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM_CATEGORY.ITEM_ID
     *
     * @return the value of PUBLIC.ITEM_CATEGORY.ITEM_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM_CATEGORY.ITEM_ID
     *
     * @param itemId the value for PUBLIC.ITEM_CATEGORY.ITEM_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM_CATEGORY.CATEGORY_ID
     *
     * @return the value of PUBLIC.ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM_CATEGORY.CATEGORY_ID
     *
     * @param categoryId the value for PUBLIC.ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated Fri Mar 11 18:29:34 EET 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}